### ISSUE TITLE
extendPermissionApis is not working with ngRestRelations

### ISSUE THREAD

**Issue by vavepl** [luyadev/luya-module-admin#206]
Hello

in NgRestModel method ngRestRelations does not check permissions from the method extendPermissionApis from Module which will cause error 500

![image](https://user-images.githubusercontent.com/7990096/44531022-0e796a00-a6f0-11e8-9699-8b6a97a16993.png)

**Comment by nadar** [comment]
@vavepl Its already a few days ago, do you have more informations what causes this problem?

**Comment by vavepl** [comment]
@nadar https://luyadev.slack.com/archives/C6MDMS28G/p1535032303000100 we talking about it on slack. I think you will remember

![image](https://user-images.githubusercontent.com/7990096/49309168-9e426780-f4da-11e8-9550-ac52f6bd26ed.png)

**Comment by nadar** [comment]
Thanks! It's sometimes hard to remember all those informations.

**Comment by nadar** [comment]
I did some research cause i wanted to fix that. In fact this is not possible with extends api permissions because menu entries also must contain a controller path for route (the one which displays the crud template), this route information is only available trough menu entry and therefore this is also the difference between the response of auth->matchApi() and for example adminmenu->getApiDetail() as the menu can provide information the auth system can not.
