### ISSUE TITLE
Issue request: Hierarchical view of hierarchical records (like categories)

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#220]
For hierarchical data like categories and sub-categories, it would be helpful to have the hierarchies visualized in the CRUD view, something like this:

![hierarchical crud 1](https://user-images.githubusercontent.com/3786245/46603462-70046500-caf3-11e8-8c51-938632d2b763.jpg)

![hierarchical crud 2](https://user-images.githubusercontent.com/3786245/46603485-78f53680-caf3-11e8-8346-579c40474451.png)

The records should still be sortable, but the sorting should take place per hierarchy level. Example for sorting from A-Z:

A
-- A
-- B
---- A
---- B
---- C
-- C
B
-- A
-- B
C

**Comment by nadar** [comment]
I am going to close this issue because:

- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our slack team: slack.luya.io. We try to keep our issue tracker as clean as possible in order to focus on active issues.
