### ISSUE TITLE
flushImageArray() problem

### ISSUE THREAD

**Issue by dven84** [luyadev/luya-module-admin#254]
https://github.com/luyadev/luya-module-admin/blob/d27f73623d08a3d719e34de83ccb667bd2694a6d/src/storage/BaseFileSystemStorage.php#L697

### What steps will reproduce the problem?

luya-module-admin v.1.2.3
1) create new image filter
2) open page:
```
foreach ($articles as $article) {
  echo Yii::$app->storage->getImage($article->image_id)->applyFilter('new-filter')->source;
}
```

### What do you get instead? 
`
ERROR Call to a member function applyFilter() on boolean
`

https://github.com/luyadev/luya-module-admin/blob/d27f73623d08a3d719e34de83ccb667bd2694a6d/src/storage/BaseFileSystemStorage.php#L360

And in next iteration `$this->imagesArray[$imageId]` is not exist

**Comment by nadar** [comment]
I am unable to reproduce problem, you exceptions says that `Yii::$app->storage->getImage($article->image_id)` seems to be false, so mabye there is just no image found. Because the problem is not about the filter - it can not even try to apply the filter. Do you have some more informations? What if you add another check if image exists? Like `$image = ...; if ($image) { // apply }`

**Comment by dven84** [comment]
![luya](https://user-images.githubusercontent.com/10542161/53478307-51017200-3a98-11e9-8a6b-189cf6a45e35.gif)

**Comment by nadar** [comment]
@dven84 thanks! That looks interesting :-)

**Comment by nadar** [comment]
I will fix it asap! Thanks for the report @dven84
