### ISSUE TITLE
Readonly values when updating CRUD record

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-admin#264]
Sometimes you want to display a value in the update form that should not be edited (like the creation and update datetime of the record). It would be good to be able to make such values readonly.

**Comment by nadar** [comment]
= add readonly option for datetime ngrest plugin?

**Comment by rolandschaub** [comment]
It would be better to make this option available to all kinds of data types.

**Comment by nadar** [comment]
This is not possible as the plugins are rendering the ouput different.

datetime => datetime
textarea => nl2br
image => <img src>

etc.

**Comment by jettero777** [comment]
+1 for adding readonly feature for every plugin.
There are many use cases when a user should not change some DB fields but should be able to read data from it. Of course we can restore old values during update processing, but it is poor UX to let user change a field and don't save changes.
Also a mature CMS allows to restrict access to model's fields per backend usergroup. But probably it is another feature.

**Comment by ifuratdev** [comment]
+1 for adding readonly feature for all plugins.

In the list view (index page) already you are showing field values as read only. you can use similar behavior in the form edit page. Since for ready only fields no extra functionality is required.

for example: 
For the datetime field, you need only to show the datetime value but no popup to update the datetime value. which is similar to the behavior datetime on the list page. and the same thing for the image field

**Comment by ifuratdev** [comment]
+1 for adding readonly feature for all plugins.

In the list view (index page) already it is showing field values as read only. we can use similar behavior in the form edit page. Since for ready only fields no extra functionality is required.

for example:
For the datetime field, you need only to show the datetime value but no popup to update the datetime value. which is similar to the behavior datetime on the list page. and the same thing for the image field and so on.

see image below for clarification

<img width="640" alt="read-only fields2" src="https://user-images.githubusercontent.com/18122838/63684396-7b44aa00-c805-11e9-974d-60da45b29d99.png">

**Comment by ifuratdev** [comment]
+1 for adding readonly feature for all plugins.

In the list view (index page) already it is showing field values as read only. we can use similar behavior in the form edit page. Since for ready only fields no extra functionality is required.

for example:
For the datetime field, we need only to show the datetime value but no popup to update the datetime value. which is similar to the behavior datetime on the list page. and the same thing for the image field and so on.

see image below for clarification

<img width="640" alt="read-only fields2" src="https://user-images.githubusercontent.com/18122838/63684460-a16a4a00-c805-11e9-964f-75f60e4b33cd.png">

**Comment by nadar** [comment]
With version 3.0 you will be able to use 'readonly' => true
