### ISSUE TITLE
i18n model fields store values in frontend

### ISSUE THREAD

**Issue by cheerymagicsoftware** [luyadev/luya-module-admin#279]
The Proposal to improve. 
When we define fields in public property $i18n of \luya\admin\ngrest\base\NgRestModel 
and then save/update them from frontend (or another plases), they are stored in raw form without "json" wrapper. Example:
We have 2 Languages in admin [en, de]

	class Article extends NgRestModel
	{
		...
		
		public $i18n = ['name', 'sku'];
		
		....
	}

Frontend Controller:

	class DefaultController extends Controller
	{
		public function actionParse()
		{
			$article = Article::find()->where(['id' => '1'])->one();
			$article->name = 'Jeans';
			$article->sku = 482452355125;
			$article->save();
		}
               ...
	}

tbl_article
name 	| sku
Jeans	| 482452355125

In admin area table these values is not visible!

Proposal: add to NgRestModel method beforeSave (it's for string values :)):

	abstract class NgRestModel extends ActiveRecord implements GenericSearchInterface, NgRestModelInterface
	{
		...
		public function beforeSave($insert)
		{
			foreach($this->attributes as $attr => $value){
				if($this->isI18n($attr) && !\luya\helpers\Json::isJson($value)) {
					$getLang = \Yii::$app->adminLanguage->getLanguages();
					$langs = \yii\helpers\ArrayHelper::getColumn($getLang,'short_code');
					$multiValue = [];
					foreach($langs as $lang => $val) {
						$multiValue[$lang] = $value;
					}
					$this->{$attr} = \luya\admin\helpers\I18n::encode($multiValue);
				}
			}

			return parent::beforeSave($insert);
		}
		...		
	}
	
After that 
tbl_article
name 								| sku
{"en":"Jeans","de":"Jeans"}			| {"en":"482452355125","de":"482452355125"}
Thanks.

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
