### ISSUE TITLE
NgRest SelectModel label for field based on the same model

### ISSUE THREAD

**Issue by mastadont08** [luyadev/luya-module-admin#299]
### What steps will reproduce the problem?
Trying to setup SelectModel plugin:
```
'parent_id' => [
                'selectModel',
                'modelClass' => self::class,
                'valueField' => 'id',
                'labelField' => 'name',
            ],
```
labelField can be lambda-function as well

Issue appears only in list-view. create/update is ok.
### What is the expected result?
parent_id field renders as the value of labelField

### What do you get instead? (A Screenshot can help us a lot!)
parent_id field renders as valueField

### LUYA Check output (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

http://joxi.ru/v296doVHZYBzvA

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | "luyadev/luya-core" : "^1.0", "luyadev/luya-module-admin" : "~1.2.0", "luyadev/luya-module-cms" : "^1.0", "luyadev/luya-bootstrap3" : "^1.0", "luyadev/luya-generic" : "^1.0"
| PHP Version      | 7.2
| Platform         | nginx/1.15.10
| Operating system | MacOs 10.14.4 (18E226)

**Comment by nadar** [comment]
Sadly, self referenced ng rest models do not work :-(

**Comment by nadar** [comment]
Use another select type like async instead

**Comment by nadar** [comment]
I am going to close this issue because:

- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our slack team: slack.luya.io. We try to keep our issue tracker as clean as possible in order to focus on active issues.
