### ISSUE TITLE
logged out on changing IP address

### ISSUE THREAD

**Issue by ifuratdev** [luyadev/luya-module-admin#346]
### What steps will reproduce the problem?
If you login from IP Address 1 and change the device IP address then the user is logged out

Full details:
For mobile users normally they switch between Mobile networks and WiFi , which results in changing the IP address.

This change in IP address results in logging out the user, which is bad user experience

**Comment by nadar** [comment]
Thanks for the research. I don't think we should switch of this behavior, as its a security mechanism. But maybe we could add an option to disable the feature with a configuration.

**Comment by ifuratdev** [comment]
makes sense to have it as an option, as it is really bad user experience to keep logging the user off

**Comment by nadar** [comment]
Yes its a bad user experience, but allowing adresses from "untrusted sources" (as the source changes after login) might be even more bad....

**Comment by nadar** [comment]
(we have a similar problem with google load balancers and HTTP_X_FORWARDED_FOR)

**Comment by ifuratdev** [comment]
i agree that changing ip might cause security issue.

The question is it a common behavior to log off a user due to IP change?
If we check services that require login like Facebook, Gmail, any CRM system, Slack, any  other service that require login, are they logging the user off due to IP change?

This will determine the common behavior users used to have

**Comment by nadar** [comment]
And its not because your application is running behind a Load balancer?

**Comment by ifuratdev** [comment]
i'm not using a load balancer, 
But load balancer might cause the same problem since IP might change

**Comment by nadar** [comment]
Yes. But allowing x forwarded from untrusted sources is dangerous, as i am actually looking into this deeper now. 

+ See this discussion: https://github.com/yiisoft/yii2/issues/16122
+ Also take a deeper look into this section! Because yii knows how to deail with x forwarded header as long as its a trusted source. https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L175-L240

**Comment by ifuratdev** [comment]
So, I think the solution might be like this:
When the user login take the IP (not the forwarded  IP) and record it in the DB as you are already doing right now (no change here)

Make checking IP address on every request optional (through configuration) as you suggested in your first reply above, my suggestion to make it disabled by default.

**Comment by nadar** [comment]
1. in the load balancer case its better to configure your application the way it gets the users IP - otherwise storing IP-Adresses makes no sense at all.....
2. in your case: i would say there is no reason the run your own application behind vpns unless you want to do something "bad". So yes, we can have such an option but it won't be disabled by default as we are not allowing ip spoofing!

**Comment by ifuratdev** [comment]
> 2. in your case: i would say there is no reason the run your own application behind vpns unless you want to do something "bad". So yes, we can have such an option but it won't be disabled by default as we are not allowing ip spoofing!

the case here is for mobile applications mainly, for mobile applications IP address changes very often when switching from mobile networks to WiFi and vice versa.

**Comment by nadar** [comment]
In order to "fix" that, disable secureHeaders list in request component:

```
'request' => [
    'secureHeaders' => [],
]
```

**Comment by nadar** [comment]
This behavior can be turned off by setting `'logoutOnUserIpChange ' => false` in admin module config (https://github.com/luyadev/luya-module-admin/blob/master/src/Module.php#L264-L270)
