### ISSUE TITLE
Sorting in a list view ingnores i18n fields

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#381]
### What steps will reproduce the problem?
Create a table with i18n fields. For example a table with cities where `city_name ` is an i18n field, 
For this field the data in DB stored as {“en”:”Moscow”, “ru”:”Москва”}. Populate table with some data.

Set the composition language for the admin area as RU.
Sort the table in the list view in the admin area. 

### What is the expected result?
List of cities in russian alphabetical order.

### What do you get instead? (A Screenshot can help us a lot!)
List of cities in some other order.

### The Reason
The sorting mechanism treat the JSON data as a plain text. So depends on the order of the JSON data in table (which index goes first) the user can get any result.

**Comment by Antikon** [comment]
A workaround can be done like this:
```
'sortField'  =>[
    'asc' =>  ['(ci.short_name->"$.'.Yii::$app->composition->langShortCode.'")' => SORT_ASC,
    'desc' => ['(ci.short_name->"$.'.Yii::$app->composition->langShortCode.'")' => SORT_DESC
]
```
where the `ci` is the alias for a joined table.

`->` is the `JSON_EXTRACT()` alias in MySQL (since 5.7.9 version). It should work for PostgreSQL also.

In MS SQL and Oracle `JSON_VALUE()` can be used.

The brackets `'(...)'` are needed to avoid escaping.


It seems that the logic can be implemented transparently in `generateSortAttributes()` method of the `luya\admin\ngrest\base\Api` class.

**Comment by nadar** [comment]
@Antikon this would be nice! Maybe you can start a PR and i will help on this! thank you for the search! awesome

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
