### ISSUE TITLE
Unexpected behavior of i18n fields

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-admin#393]
### What steps will reproduce the problem?
Let assume that we have a User model with `surname` and `name`. Both of them are i18n.
In addition we have an extraField 'fullName' and a getter 
```
public function getFullName()
{
    return trim($this->surname.' '.$this->name.)
}
```

And the last one is `ngRestScopes()`:
```
public function ngRestScopes()
{
    return [
        ['list', ['fullName']],
        /*['update', [surname', 'name']],*/
        ['delete', false],
    ];
}
```
### What is the expected result?
I am expecting that the `fullName` will be a plain text. However, the `fullName` is a JSON string.

**Everything is ok, when the `update` scope is uncommented.** 

It seems that until `surname` and` name` are affected by the `update` scope, their value remains raw.

As for me this is an unexpected behavior. I expect that in the `list` scope the values of i18n attributes will have vaules based on the current language regardless of `update` scope.

**Comment by nadar** [comment]
what does the ngrest extra attribute type look like?

**Comment by Antikon** [comment]
```
public function ngRestExtraAttributeTypes()
{
    return [
        'fullName'       => [
            'text',
            'sortField' => [
                'asc'  => ['surname' => SORT_ASC, 'name' => SORT_ASC],
                'desc' => ['surname' => SORT_DESC, 'name' => SORT_DESC],
            ]
        ],
}
```

**Comment by Antikon** [comment]
It seems that the "autoconversion" feature of i18n field works only if they are present in `update` scope.

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
