### ISSUE TITLE
Customize luya admin sidebar and functionality

### ISSUE THREAD

**Issue by gs63875** [luyadev/luya-module-admin#417]
Hi @nadar,

I want to customize lots of functionality like hiding CSV export, user last name and the things that I do not want to in my project that in the left side sidebar but the problem is they are in the vendor folder. how I can do that?

**Comment by nadar** [comment]
The difference of LUYA to other systems is that its "living" in the vendor, this means you can just run composer update and you will get all no shiny and fresh features without doing anything.

So this has one "down" side, if you like to have features we need to implement it in the admin as configuration. So for example if you like to hide the csv export button, we need to make a configuration which hiddes them all. 

+ create an issue
+ create a pull request

;-) would be the best option to improve also the system and your application. Otherwise commit the vendor folder and never run composer update again - or bind the luya admin module with psr4 into your project:

"luya\\admin\\" : "modules/luya/admin/in/your/application"

**Comment by nadar** [comment]
Let me know if we can assist on this, until then i will close the issue as there is no response since 10 days
