### ISSUE TITLE
Another view for  field groups

### ISSUE THREAD

**Issue by dven84** [luyadev/luya-module-admin#52]
Tabs are better when the model has many fields:

![image](https://user-images.githubusercontent.com/10542161/35677444-6491ad40-0771-11e8-82c9-0e2c47a26063.png)
What do you think? :)

**Comment by nadar** [comment]
i personally like the idea, the only things against such a chain are:

+ Its Tabs in Tabs. The tabs from (create, list, update, relations) and now tabs for groups.
+ Assuming we have 3 tabs, and 1 field in the last tab is required, the save button (which is global) would trigger a validation error from a field the user maybe can not even see. Sure we have same problem now, if the group is closed, but it looks more like "one" form.

Instead of tabs, maybe we could make the grouping more like an accordion behavior. Opening a group would close all other groups.

**Comment by nadar** [comment]
I am going to close this for now due to the fact discussion is not activ, and we already have a grouping option and the facts i mentioned above. 

(we also have to cleanup the issues from time to time to have a basic overview, please add new issues for other ideas and inputs, its very welcome.)
