### ISSUE TITLE
please update Imagine... php 8.2 maybe>>

### ISSUE THREAD

**Issue by Crazy-racoon** [luyadev/luya-module-admin#757]
update server to php8.2 - crash my code) it's okey^ but i can't update imagine pack, because module-admin need imagine 2.1, but actual version 2.3.1

**Comment by nadar** [comment]
Our luya admin imagine dependency version constraint  (^2.1) should allow you to install imagine 2.3.1 without problem

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [LUYA discussions](https://github.com/luyadev/luya/discussions))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our discussion: [LUYA discussions](https://github.com/luyadev/luya/discussions). We try to keep our issue tracker as clean as possible in order to focus on active issues.
